[package]
name = "Nosleep"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.4"
ctrlc2 = {version="3.5.9",features=["tokio"]}
enigo = "0.3.0"
log = "0.4.22"
rustlib = { path = "../rustlib" }
serde = "1.0.217"
tokio = { version = "1.42.0", features = ["full"] }
